### ISSUE TITLE
Transfer speed gradually decreases when sending large amount of files.

### ISSUE THREAD

**Issue by Trackerlist** [localsend/localsend#1657]
### Describe the bug

My english isn't sharpy so I apologize for any grammatical mistakes.

When transferring thousands of files from Android to Windows, (in my case, a folder with 7000 image files, which contains less than 1gb of data.) Localsend gradually decreases it's transfer speed. For example: After successfully transferring 100 files, transfer speed would be around 1mb/s. After 500 files, the speed drops to 600kb/s. After 1000 files, it'll be 80kb/s, and so on.

However, if I compact everything to a .zip file with 0 compression before I send it, I get a steady speed of 4mb/s on 2.4ghz wifi. It doesn't slows down, meaning that the issue is related to the quantity of files, and not the size of them.

In short: Many single files = Gradually decreases transfer speed. | One single = Maintains the same speed until it's concluded.

Encryption is disabled. Both Desktop and Mobile are running Localsend 1.15.3 (latest).

### To reproduce

Send thousands of files from Android to Desktop and see the speed slowing down.
Send the same files but inside a .zip file and transfer speed would be the same until the end.

### Expected behavior

Sending multiple files one by one should maintain the same average speed, just like when sending a single large file.

### Desktop (please complete the following information)

- OS: Windows 11
- Version: 1.15.3

### Smartphone (please complete the following information)

- Device: LgK40S
- OS: Android 10
- Version: 1.15.3

**Comment by Trackerlist** [comment]
Screenshots:

Single file
![LocalSend_18 16 12 40_m08 y2024](https://github.com/user-attachments/assets/084cb600-7e5c-4ab2-8372-d42798797eda)

Multiple files
![LocalSend_18 16 11 41_m08 y2024](https://github.com/user-attachments/assets/cafdf7a7-0137-4410-a425-01c882b6b616)

**Comment by Trackerlist** [comment]
Additionally, the same doesn't seems to happen when sending multiple files with a higher size. I tested with 600 video files that size is in the range of 1mb to 60mb. Speed starts at 5.8mb/s and in just a few seconds drops to 5.2mb/s, but keeping around that until the end.

**Comment by Tienisto** [comment]
Do you see the same bug if you send from Android to another Android/iOS/macOS/Linux?
I want to make sure that Windows is not the problem here

**Comment by Trackerlist** [comment]
Tested on Galaxy J7 2016, which is Android 8.1, 2gb ram and 32bits. The same issue happens, but way faster than from my main Android to Desktop. Since this device is really old, I don't think this was a good test.

Additionally: This slowdown happens no matter if I'm using normal wifi (router) or hotspot.

**Comment by Trackerlist** [comment]
Tested on Galaxy J7 2016, which is Android 8.1, 2gb ram and 32bits. The same issue happens, but the speed drops way faster than from my main Android to Desktop. Since this device is really old, I don't think this was a good test.

Additionally: This slowdown happens no matter if I'm using normal wifi (router) or hotspot.

**Comment by Trackerlist** [comment]
Tested on Galaxy J7 2016, which is Android 8.1, 2gb ram and 32bits. The same issue happens, but the speed drops way faster than from my main Android to Desktop, both with encryption enabled and disabled. Since this device is really old, I don't think this was a good test.

Additionally: This slowdown happens no matter if I'm using normal wifi (router) or hotspot.

**Comment by Tienisto** [comment]
@Trackerlist can you checkout the latest version 1.15.4?

**Comment by Trackerlist** [comment]
Tested on from Android to Windows and Android to Linux. Using hotspot 2.4ghz. Speeds won't gradually decreases anymore. Transfer speed are steady now, meaning the issue was fixed!

![NVIDIA_Overlay_20 10 44 37_m08 y2024](https://github.com/user-attachments/assets/f87ccdef-1867-4d94-b6c0-ecd24ee105af)

I've also noticed two things that might be good to know:

Localsend cannot transfer more than two files per second, meaning that transfer speed will slowdown depending of the file size. For example: If I send files with 2mb each one, the speed will be 4mb/s. If i send files with 10kb each, the speed will adapt to 20kb/s. It can't send more than 2 files per second.

When turning off Android's screen and waiting for about 5 minutes, Localsend stops sending files and just unfreezes when the screen is on again, meaning the device cannot be on stand-by for too long. When setting Auto Screen Off to Never, this no longer happens.

**Comment by Trackerlist** [comment]
Localsend finished transferring successfully!
![image](https://github.com/user-attachments/assets/e74e7d4d-8f23-4960-a4dc-ab39b09f0b01)

Before, I faced some weird bug that freezed the transfer. Both desktop and android apps were working normaly, but it seems they lost connection somehow and stopped sending and receiving files.

I could see this same information on both android and desktop. After I cancel the transfer on desktop, android didn't auto-canceled like always do, reinforcing that it may be caused by a loss of connection, but I don't know what caused it:
![NVIDIA_Overlay_20 15 24 59_m08 y2024](https://github.com/user-attachments/assets/a05088f2-d5ec-4406-aecb-fdfb888ada5f)

After I retried again, everything just works. Thank you for this amazing app!

**Comment by nv6** [comment]
This is absolutely NOT fixed and is still causing major issues when transferring from iOS 26 to Android 16. Both devices are connected to the same 5GHz SSID, and the Android device's link speed is 1700/2100 Mbps (Tx/Rx).

**Comment by quuuuii** [comment]
Still not fixed, android to ios

**Comment by nv6** [comment]
Just use LANdrop at this point instead of this buggy unmaintained garbage lol

**Comment by Doxxy00** [comment]
as of 2026 aug 9, the problem still persists. i am sending from a macbook air m5, running latest macos 26.6.1 to a latest win10 ver. i started one hour ago, with 2MB/s, now its down to 1.3MB/s, sending time doubled
