### ISSUE TITLE
Bug Report: black app screen after clicked back button from Share via link screen on macOS

### ISSUE THREAD

**Issue by CakeAL** [localsend/localsend#2061]
### Describe the bug

After clicked back button on Share via link screen, the app screen goes black. I think that's different form #1943 

### To reproduce

1. Go to 'Share via link' screen
2. Click on 'Back Button'
3. See error

### Expected behavior

return to the main page

### Screenshots

https://github.com/user-attachments/assets/0d53473e-b312-4ca8-b226-6751dc824a14

### Desktop (please complete the following information)

- OS: macOS 15.1
- Version: 1.16.1

**Comment by Tienisto** [comment]
I can only reproduce this if I tap twice on the back button. Regardless, this should be fixed now!

**Comment by West-Pavilion** [comment]
it still exists at 1.61.1
I have reproduced it on both Windows 10 and Debian 12
