### ISSUE TITLE
The titlebar is white on dark mode [KDE Plasma]

### ISSUE THREAD

**Issue by r0shd** [localsend/localsend#2241]
### Describe the bug

Hello. As title says, the titlebar is white on dark mode.

### To reproduce

1. Open LocalSend
2. White titlebar on dark mode

### Expected behavior

1. Open LocalSend
2. The titlebar should respect the system theme.

### Screenshots

![Image](https://github.com/user-attachments/assets/8afa2d3a-f708-439a-91cc-b652ccac59de)

### Desktop (please complete the following information)

OS: Fedora Kinoite
Version: 41

**Comment by JStrategic** [comment]
Having this same issue as well. Even after manually selecting dark for the theme the title bar is still white.

**Comment by newart3** [comment]
I think this is a flutter issue: https://github.com/flutter/flutter/issues/111453. You can fix it by setting the env var `GTK_CSD=0` when launching localsend:
`GTK_CSD=0 localsend`

or if using flatpak (you need to run this only once):
`sudo flatpak override --env=GTK_CSD=0 org.localsend.localsend_app`

IMO localsend should just not draw custom header on linux (https://github.com/AppFlowy-IO/AppFlowy/pull/5991).

**Comment by Merrit** [comment]
This was resolved with https://github.com/localsend/localsend/pull/2360 and should be in the next release.

**Comment by ArqamQazi** [comment]
The issue is still present. https://github.com/localsend/localsend/issues/3349 https://github.com/localsend/localsend/issues/3053
