### ISSUE TITLE
Sharesheet not working On Android

### ISSUE THREAD

**Issue by idjfia** [localsend/localsend#31]
Select file(s) in file app,then click localSend on Android Sharesheet,just jump to _Receive_ and will not transfer file(s).

**Comment by Tienisto** [comment]
Hi, I am also getting this bug when LocalSend is previously not open. When LocalSend is just minimized, then it works.

Is this behaviour on your side the same?

**Comment by idjfia** [comment]
> Hi, I am also getting this bug when LocalSend is previously not open. When LocalSend is just minimized, then it works.
> 
> Is this behaviour on your side the same?

It still doesn't work, and crashes occasionally.

Thank you for your nice work.

My device model: Pixel OG
Android version: 10

**Comment by Tienisto** [comment]
Does in work in `v1.6.1`? I have fixed some bugs there.

**Comment by idjfia** [comment]
> Does in work in `v1.6.1`? I have fixed some bugs there.

still doesn't work, jump to _Send_ page only when sharing photo(s).

Excuse me that my English is poor.

**Comment by Tienisto** [comment]
I think that it may happen in file names with Chinese characters. Can you test it please?

Probably related to https://github.com/ShoutSocial/share_handler/pull/39

**Comment by idjfia** [comment]
> 

It also happen in file names with English characters.
![Screenshot](https://user-images.githubusercontent.com/16682639/215267061-fe1cde19-fb88-4c54-bb31-f4c52c08330b.png)

**Comment by Tienisto** [comment]
Does it work in `v1.6.2`?

If not, then I have no idea how to fix this. This is handled by another dependency that I don't manage.

**Comment by idjfia** [comment]
> Does it work in `v1.6.2`?
> 
> If not, then I have no idea how to fix this. This is handled by another dependency that I don't manage.

Problem solved! it works perfectly on Files by Google and other apps!

Thank you for your nice work again!

**Comment by Tienisto** [comment]
Thanks. Your feedback helped alot!
