### ISSUE TITLE
Feature request: Support IPv6

### ISSUE THREAD

**Issue by lc6464** [localsend/localsend#549]
### Is your feature request related to a problem? Please describe.

I have noticed that the LocalSend software does not support IPv6. When I use direct sending, I can use IPv4 addresses and domain names, but when I input an IPv6 address, it displays an "error". Additionally, if the domain name only has AAAA resolution without A resolution, it also displays an "error".

### Describe the solution you'd like

I would like LocalSend to work properly when I input an IPv6 address and when I input a domain name with only AAAA resolution.

Additionally, if the domain name has both A and AAAA resolutions, I would like LocalSend to prioritize using the IPv6 address corresponding to the AAAA resolution, and fallback to IPv4 if it fails.

Furthermore, I hope that LocalSend can add support for NetBIOS names, allowing for fast sending within local networks with a large number of devices.

Lastly, I would prefer that LocalSend's network alias defaults to using the device's NetBIOS name.

### Describe alternatives you've considered

I believe IPv6 support is irreplaceable. If it's not possible to directly access the address corresponding to the NetBIOS name, this functionality can be abandoned. If it's not possible to obtain the NetBIOS name of the current device, consider allowing the user to manually enter the network alias during the initial startup.

### Additional context

None.

**Comment by lc6464** [comment]
By the way, I hope that when sending text via Web URI, it can be displayed directly with a copy button, instead of indirectly transferring it through a TXT file.

**Comment by yutouyes** [comment]
Hello, any update? I still get "error" when try to use IPv6

**Comment by Toorero** [comment]
Also, it would be great if IPv6 support works only by using link-local IPv6 addresses like on direct LAN connections between two machines.

**Comment by Toorero** [comment]
I'm wondering if any maintainer could chime in and lay out a path on how to move forward with this issue? Because the IPv4 broadcast is also part of the protocol-standard somehow.

**Comment by Tienisto** [comment]
The next step would be to also bind the HTTP server to ipv6. Currently, it binds to `0.0.0.0`.
I couldn't find documentation to bind to ipv4 and ipv6 at the same time.
The next update will likely have the http server migrated to Rust so that ipv6 should be supported also.
The next update will be in Dezember or January.

**Comment by felixls** [comment]
+1

My LAN is IPV6 only using option 108 in DHCP (https://www.rfc-editor.org/rfc/rfc8925.html), so, Localsend doesn't work properly, and particularly on android not at all.

**Comment by Antosser** [comment]
Imo support for IPv6 is essential for an app like this, especially for link-local connections. Since IPv6 does not require any configuration or DHCP for link-local connections, you would be able to simply connect two computers with an ethernet cable and share files with no configuration

Afaik, this is not possible with IPv4 right now

**Comment by jthoward64** [comment]
It also breaks on iOS devices that are using their CLAT. On an IPv6-mostly network devices with a CLAT get a v4 address like 192.0.0.3 or similar which is only routable on the local device and gets translated to an IPv6 address automatically. This is an issue because localsend assumes that is the device's LAN address.

**Comment by Antosser** [comment]
You're right that CLAT will cause confusion for the device, since the address is not routable from the outside. But this shouldn't be a difficult fix.

You could, for example, prefer IPv6 over IPv4. Most networks that deploy CLAT are actually IPv6-first networks, so devices have a fully routable IPv6 address (global or link-local). If LocalSend supports IPv6 sockets and advertises IPv6 addresses alongside IPv4, peers can connect using IPv6 when IPv4 is not usable.

It would also be a good idea to ignore any address in the `192.0.0.0/29` CLAT IPv4 range.

So instead of assuming the reported IPv4 address is the LAN address, LocalSend should support IPv6 and ignore CLAT IPv4 ranges. On IPv6-mostly networks, this will allow devices (including iOS) to communicate normally.

**Comment by jthoward64** [comment]
> You could, for example, prefer IPv6 over IPv4. Most networks that deploy CLAT are actually IPv6-first networks, so devices have a fully routable IPv6 address (global or link-local). If LocalSend supports IPv6 sockets and advertises IPv6 addresses alongside IPv4, peers can connect using IPv6 when IPv4 is not usable.

That's the RFC compliant behavior as I understand it (https://www.rfc-editor.org/rfc/rfc6724).

**Comment by wanghaora** [comment]
Unconsciously, three years have passed, but this problem still hasn't been solved. by V1.17.0

**Comment by jthoward64** [comment]
Perhaps either mdns or IPv6 multicast might be ways to go here?

**Comment by Rajala1404** [comment]
The main branch at least supports sending over IPv6 via manual IP entry (WebRTC discovery works but actual sending fails immediately when using WebRTC discovered devices)

**Comment by Tienisto** [comment]
This should be resolved in v1.18.0 which will be released in the next weeks.

**Comment by ItzDankoo** [comment]
Hello, IPv6 still isn't working for Windows 11 in app version v1.18.0, but it is already working in the Android mobile app (version v1.18.1).
